"""dedup

Revision ID: 143fa03531ec
Revises: 313dc8c6b10f
Create Date: 2021-07-14 17:13:20.499903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '143fa03531ec'
down_revision = '313dc8c6b10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_uid', sa.String(), nullable=True),
    sa.Column('stages_status', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tmp_table', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tmp_table', 'categories', ['category_id'], ['id'])
    op.drop_column('tmp_table', 'category')
    op.add_column('version_items', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'version_items', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version_items', type_='foreignkey')
    op.drop_column('version_items', 'category_id')
    op.add_column('tmp_table', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tmp_table', type_='foreignkey')
    op.drop_column('tmp_table', 'category_id')
    op.drop_table('deduplication')
    # ### end Alembic commands ###
