"""dedup teble change
Revision ID: 2091b491c9a3
Revises: 7e657ffbb933
Create Date: 2021-07-28 15:47:18.743462
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2091b491c9a3'
down_revision = '7e657ffbb933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diff')
    op.add_column('deduplication', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('deduplication', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('deduplication', sa.Column('task_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deduplication', 'task_status')
    op.drop_column('deduplication', 'started_at')
    op.drop_column('deduplication', 'created_at')
    op.create_table('diff',
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['data_items.id'], name='diff_item_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], name='diff_version_id_fkey'),
    sa.PrimaryKeyConstraint('version_id', 'item_id', name='diff_pkey')
    )
    # ### end Alembic commands ###
