"""Add modetation tbl

Revision ID: 313dc8c6b10f
Revises: 6ed2437c7609
Create Date: 2021-07-12 17:17:39.434693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313dc8c6b10f'
down_revision = '6ed2437c7609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('moderation',
    sa.Column('src', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('src_media_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('general_category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('src', 'file')
    )
    op.create_table('tmp_table',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['data_items.id'], ),
    sa.ForeignKeyConstraint(['node_name'], ['versions.name'], ),
    sa.PrimaryKeyConstraint('item_id', 'node_name', 'category')
    )
    op.create_table('version_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['data_items.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'version_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_items')
    op.drop_table('tmp_table')
    op.drop_table('moderation')
    op.drop_table('data_items')
    # ### end Alembic commands ###
