"""relations

Revision ID: 63bb8961985a
Revises: 6524f2a4f051
Create Date: 2021-08-03 22:18:50.290661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bb8961985a'
down_revision = '6524f2a4f051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('changes_item_id_fkey', 'changes', type_='foreignkey')
    op.create_foreign_key(None, 'changes', 'data_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('diff_item_id_fkey', 'diff', type_='foreignkey')
    op.create_foreign_key(None, 'diff', 'data_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tmp_table_item_id_fkey', 'tmp_table', type_='foreignkey')
    op.create_foreign_key(None, 'tmp_table', 'data_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('version_items_item_id_fkey', 'version_items', type_='foreignkey')
    op.create_foreign_key(None, 'version_items', 'data_items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version_items', type_='foreignkey')
    op.create_foreign_key('version_items_item_id_fkey', 'version_items', 'data_items', ['item_id'], ['id'])
    op.drop_constraint(None, 'tmp_table', type_='foreignkey')
    op.create_foreign_key('tmp_table_item_id_fkey', 'tmp_table', 'data_items', ['item_id'], ['id'])
    op.drop_constraint(None, 'diff', type_='foreignkey')
    op.create_foreign_key('diff_item_id_fkey', 'diff', 'data_items', ['item_id'], ['id'])
    op.drop_constraint(None, 'changes', type_='foreignkey')
    op.create_foreign_key('changes_item_id_fkey', 'changes', 'data_items', ['item_id'], ['id'])
    # ### end Alembic commands ###
