"""changes_2

Revision ID: 6524f2a4f051
Revises: 1f9449ae3224
Create Date: 2021-08-02 11:02:09.506602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6524f2a4f051'
down_revision = '1f9449ae3224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('changes', sa.Column('new_category', sa.Integer(), nullable=False))
    op.drop_column('changes', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('changes', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('changes', 'new_category')
    # ### end Alembic commands ###
