"""empty message
Revision ID: 9cb81b29e6b1
Revises: 7b176dc0ee69
Create Date: 2021-07-20 16:54:00.978800
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cb81b29e6b1'
down_revision = '7b176dc0ee69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_uid', sa.String(), nullable=True),
    sa.Column('stages_status', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deduplication')
    # ### end Alembic commands ###

